---
name: Lua For SM5
baseurl: /Lua-For-SM5
timezone: America/New_York


# Dependencies
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  Considerations:
    output: true
  Actors:
    output: true
  Singletons:
    output: true
  Examples:
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"