---
name: Lua For SM5
baseurl: /Lua-For-SM5
timezone: America/New_York


# Dependencies
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge


collections:
  chapter-0:
    output: true
  chapter-1:
    output: true
  chapter-2:
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"