baseurl: "/Lua-For-SM5"

# Dependencies
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"
