---
name: Lua For SM5
baseurl: /Lua-For-SM5
timezone: America/New_York


# Dependencies
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  Introduction:
    output: true
    sequence: 0
  Actors:
    output: true
    sequence: 1
  Singletons:
    output: true
    sequence: 2
  Best_Practices:
    output: true
    sequence: 3
  Examples:
    output: true
    sequence: 4

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"