---
name: Lua For SM5
baseurl: /Lua-For-SM5

# Dependencies
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge


collections:
  chapter_0:
    output: true
  chapter_1:
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"